# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

http:
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ssl_profile: modern
  ip_ban_enabled: true
  login_attempts_threshold: 10

history:
  exclude:
    entities:
      - binary_sensor.workday
      - sensor.external_ip
    entity_globs:
      - sensor.date*
      - sun.*
      - weather.*

logbook:
  exclude:
    entities:
      - binary_sensor.workday
      - sensor.external_ip
    entity_globs:
      - sensor.date*
      - sun.*
      - weather.*

binary_sensor:
  - platform: workday
    name: Workday
    country: US

device_tracker:
  - platform: ping
    new_device_defaults:
      track_new_devices: true
    hosts: !secret ping_hosts

notify:
  - platform: telegram
    name: Telegram Group
    chat_id: !secret telegram_chat_id

sensor:
  - platform: time_date
    display_options:
      - date
      - date_time
      - date_time_iso
      - date_time_utc

tts:
  - platform: google_translate

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
